# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: qqreads

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/20 * * *'
  watch:
    types: started
  repository_dispatch:
    types: qqreads
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
      - name: '运行 【QQ阅读】'
        run: |
          node qqreads.js
        
